  // GENERATED by scripts/gen-help-shots.mjs — do not edit by hand.
  // Intrinsic CSS size of each Help screenshot, used to reserve its box before
  // the lazily-loaded image arrives. Re-run the script after changing a shot.
  export const HELP_SHOTS = {
    "settings-years": {
      "w": 917,
      "h": 115
    },
    "entry-form": {
      "w": 680,
      "h": 502
    },
    "budget-toolbar": {
      "w": 521,
      "h": 34
    },
    "budget-grid": {
      "w": 915,
      "h": 320
    },
    "row-menu": {
      "w": 180,
      "h": 276
    },
    "bva": {
      "w": 917,
      "h": 300
    },
    "dashboard-kpis": {
      "w": 917,
      "h": 126
    },
    "dashboard-upcoming": {
      "w": 917,
      "h": 320
    },
    "plan-goals": {
      "w": 917,
      "h": 202
    },
    "settings-backup": {
      "w": 917,
      "h": 61
    }
  };
