  // GENERATED by scripts/gen-help-shots.mjs — do not edit by hand.
  // Intrinsic CSS size of each Help screenshot, used to reserve its box before
  // the lazily-loaded image arrives. Re-run the script after changing a shot.
  const HELP_SHOTS = {
    "settings-years": {
      "w": 917,
      "h": 154
    },
    "entry-form": {
      "w": 680,
      "h": 472
    },
    "budget-toolbar": {
      "w": 521,
      "h": 29
    },
    "budget-grid": {
      "w": 915,
      "h": 320
    },
    "row-menu": {
      "w": 180,
      "h": 248
    },
    "bva": {
      "w": 917,
      "h": 300
    },
    "dashboard-kpis": {
      "w": 917,
      "h": 86
    },
    "dashboard-upcoming": {
      "w": 917,
      "h": 260
    },
    "plan-goals": {
      "w": 917,
      "h": 193
    },
    "settings-backup": {
      "w": 917,
      "h": 104
    }
  };
